### ISSUE TITLE
Minecraft doesn't open with Forge downloaded

### ISSUE THREAD

**Issue by philbibliography** [UltimMC/Launcher#253]
### Operating System

Windows

### Description of bug

After Forge is installed, Minecraft 1.12.2 crashes everytime. This issue has been signaled before but without a crash log.

The crash log is as follows:

UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.230.232.55, 54.230.232.40, 54.230.232.51, 54.230.232.58]

session.minecraft.net resolves to:
    [100.24.172.95, 34.197.32.8, 35.153.153.200]

textures.minecraft.net resolves to:
    [2620:1ec:4f:1::44, 2620:1ec:4e:1::44, 13.107.237.44, 13.107.238.44]

api.mojang.com resolves to:
    [54.192.235.56, 54.192.235.48, 54.192.235.15, 54.192.235.94]

Minecraft folder is:
C:/Users/Alex/Desktop/UltimMC/instances/1.12.2/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Alex/Desktop/UltimMC/instances/1.12.2/natives

Libraries:
  C:/Users/Alex/Desktop/UltimMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2859/forge-1.12.2-14.23.5.2859-universal.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/ow2/asm/asm-debug-all/5.2/asm-debug-all-5.2.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2_mc/scala-continuations-library_2.11-1.0.2_mc.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2_mc/scala-continuations-plugin_2.11.1-1.0.2_mc.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/Alex/Desktop/UltimMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Alex/Desktop/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [❌] CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar.disabled (disabled)
  [❌] DynamicTrees-1.12.2-0.9.29.jar.disabled (disabled)
  [❌] IGW-Mod-1.12.2-1.4.4-15-universal.jar.disabled (disabled)
  [❌] Immersive+Vehicles-1.12.2-22.5.0.jar.disabled (disabled)
  [❌] ImmersiveEngineering-0.12-98.jar.disabled (disabled)
  [❌] ImmersiveRailroading-1.12.2-forge-1.9.1.jar.disabled (disabled)
  [❌] OpenComputers-MC1.12.2-1.7.7+5413028.jar.disabled (disabled)
  [❌] terrarium-1.1.9.jar.disabled (disabled)
  [❌] TrackAPI-1.2.jar.disabled (disabled)
  [❌] UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar.disabled (disabled)
  [❌] UNU+Civilian+Pack+[MTS]+1.12.2-21.3.0-5.3.2.jar.disabled (disabled)
  [❌] UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar.disabled (disabled)

Params:
  --username  --version 1.12.2 --gameDir C:/Users/Alex/Desktop/UltimMC/instances/1.12.2/.minecraft --assetsDir C:/Users/Alex/Desktop/UltimMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/Alex/Desktop/UltimMC/injectors/authlib-injector-1.2.1.jar=ely.by, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6528m, -Duser.language=en]

Minecraft process ID: 19576

[authlib-injector] [INFO] Logging file: C:\Users\Alex\Desktop\UltimMC\instances\1.12.2\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.1
[authlib-injector] [INFO] Authentication server: https://ely.by
[authlib-injector] [INFO] Redirect to: https://account.ely.by/api/authlib-injector
[authlib-injector] [INFO] Disabled Mojang namespace
Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

Open Minecraft 1.12.2 with Forge installed

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by philbibliography** [comment]
Solved the issue myself, needed to use Java Developer Kit (JDK) 1.8 as java version.
