### ISSUE TITLE
mods like rlcraft wont load

### ISSUE THREAD

**Issue by bluedragon93** [UltimMC/Launcher#284]
### Description of bug

every time i try to load rlcraft it comes up with a error but simply optimised mod works fine,
it sends this error when i try to load it:
Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Steps to reproduce

load rlcraft, or alot of the technic mods in the launcher

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Likely not related to UltimMC, closing.
