### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Emelmr** [UltimMC/Launcher#301]
### Operating System

Windows

### Description of bug

crashes while starting game

### Steps to reproduce

launch launcher boom 10seconds later crash

### Suspected cause

logs 
UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [127.0.0.1]

session.minecraft.net resolves to:
    [13.107.246.73, 13.107.213.73]

textures.minecraft.net resolves to:
    [13.107.246.73, 13.107.213.73]

api.mojang.com resolves to:
    [13.107.246.73, 13.107.213.73]

Minecraft folder is:
C:/Users/tsuka/Desktop/UltimMC/instances/troll hack2/.minecraft

Java path is:
C:/Program Files/Amazon Corretto/jdk1.8.0_382/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_382, using 64-bit architecture, from Amazon.com Inc..

Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/tsuka/Desktop/UltimMC/instances/troll hack2/natives

Libraries:
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/tsuka/Desktop/UltimMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/tsuka/Desktop/UltimMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] 1.12.2-OptiFine_HD_U_G5.jar

Params:
  --username <ACCESS TOKEN> --version 1.12.2 --gameDir C:/Users/tsuka/Desktop/UltimMC/instances/troll hack2/.minecraft --assetsDir C:/Users/tsuka/Desktop/UltimMC/assets --assetIndex 1.12 --uuid  --accessToken <ACCESS TOKEN> --userType Local --versionType release

Window size: 854 x 480

Java Arguments:
[-javaagent:C:/Users/tsuka/Desktop/UltimMC/injectors/authlib-injector-1.2.3.jar=http://localhost:52363, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en]

Minecraft process ID: 3656

[authlib-injector] [INFO] Logging file: C:\Users\tsuka\Desktop\UltimMC\instances\troll hack2\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: http://localhost:52363
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Enable MC-52974 Workaround
[authlib-injector] [INFO] Httpd is running on port 52417
[authlib-injector] [INFO] Transformed [bua] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [MC-52974 Workaround]
[20:51:50] [Client thread/INFO]: Setting user: <ACCESS TOKEN>
[20:51:54] [Client thread/INFO]: LWJGL Version: 2.9.4
[20:51:54] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.createWindow(Display.java:306) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:848) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at org.lwjgl.opengl.Display.create(Display.java:757) ~[lwjgl-2.9.4-nightly-20150209.jar:?]
	at bib.at(SourceFile:622) [minecraft-1.12.2-client.jar:?]
	at bib.aq(SourceFile:458) [minecraft-1.12.2-client.jar:?]
	at bib.a(SourceFile:404) [minecraft-1.12.2-client.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [minecraft-1.12.2-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
---- Minecraft Crash Report ----
// My bad.

Time: 9/23/23 8:51 PM
Description: Initializing game

org.lwjgl.LWJGLException: Pixel format not accelerated
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
	at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
	at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:247)
	at org.lwjgl.opengl.Display.createWindow(Display.java:306)
	at org.lwjgl.opengl.Display.create(Display.java:848)
	at org.lwjgl.opengl.Display.create(Display.java:757)
	at org.lwjgl.opengl.Display.create(Display.java:739)
	at bib.at(SourceFile:635)
	at bib.aq(SourceFile:458)

-- Initialization --
Details:
Stacktrace:
	at bib.a(SourceFile:404)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_382, Amazon.com Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Amazon.com Inc.
	Memory: 401097296 bytes (382 MB) / 514850816 bytes (491 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\tsuka\Desktop\UltimMC\instances\troll hack2\.minecraft\crash-reports\crash-2023-09-23_20.51.55-client.txt
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
Unable to reproduce, issue lacking information.
