### ISSUE TITLE
Cant Run by UUID ?

### ISSUE THREAD

**Issue by ghost** [UltimMC/Launcher#308]
### Operating System

Windows

### Description of bug

Run 1.20.2 Cant Start

### Steps to reproduce

Create a 1.20.2 and start it

### Suspected cause

Failed to start Minecraft:
java.lang.IllegalArgumentException: Invalid UUID string: 
	at java.base/java.util.UUID.fromString1(UUID.java:280)
	at java.base/java.util.UUID.fromString(UUID.java:258)
	at com.mojang.util.UndashedUuid.fromStringLenient(UndashedUuid.java:14)
	at net.minecraft.client.main.Main.main(SourceFile:151)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by ayqazi** [comment]
See #303
