### ISSUE TITLE
1.20.2 won't launch with Forge

### ISSUE THREAD

**Issue by NynaSunner** [UltimMC/Launcher#324]
### Operating System

Windows

### Description of bug

UltimMC can launch 1.20.2 vanilla with no issue, but if I install Forge it won't launch even if no mods are enabled. I've tried downgrading Forge and using different Java versions (17, 19, 20, 21) with no luck. Disabling Forge makes it work again.

### Steps to reproduce

- Create a vanilla 1.20.2 instance
- Add Forge, any version
- Launch normally or in offline mode

### Suspected cause

```
UltimMC version: 0.7.0-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.154.22.44, 18.154.22.84, 18.154.22.22, 18.154.22.64]

session.minecraft.net resolves to:
    [13.107.213.43, 13.107.246.43]

textures.minecraft.net resolves to:
    [13.107.246.43, 13.107.213.43]

api.mojang.com resolves to:
    [13.107.213.43, 13.107.246.43]


Minecraft folder is:
D:/Descargas/mmc-cracked-win32/UltimMC/instances/1.20.2/.minecraft


Java path is:
C:/Program Files/Java/jdk-19/bin/javaw.exe


Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Oracle Corporation.


Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  D:/Descargas/mmc-cracked-win32/UltimMC/instances/1.20.2/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/authlib/5.0.47/authlib-5.0.47.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-windows.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-windows-arm64.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2-natives-windows-x86.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc3/ForgeWrapper-mmc3.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/unsafe/0.9.2/unsafe-0.9.2.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/securemodules/2.2.3/securemodules-2.2.3.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/accesstransformers/8.1.1/accesstransformers-8.1.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/eventbus/6.2.0/eventbus-6.2.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/forgespi/7.1.0/forgespi-7.1.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/coremods/5.1.0/coremods-5.1.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/modlauncher/10.1.1/modlauncher-10.1.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/mergetool-api/1.0/mergetool-api-1.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/bootstrap/1.2.0/bootstrap-1.2.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/fmlloader/1.20.2-48.1.0/fmlloader-1.20.2-48.1.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.2-48.1.0/fmlearlydisplay-1.20.2-48.1.0.jar
  D:/Descargas/mmc-cracked-win32/UltimMC/libraries/com/mojang/minecraft/1.20.2/minecraft-1.20.2-client.jar

Native libraries:

Mods:
  [❌] BetterPvP_23.8.4_Forge_1.20.2.jar.disabled (disabled)
  [❌] BiomesOPlenty-1.20.2-18.1.0.612.jar.disabled (disabled)
  [❌] Pixelmon-1.20.2-9.2.5-universal.jar.disabled (disabled)
  [❌] TerraBlender-forge-1.20.2-3.1.0.21.jar.disabled (disabled)
  [❌] XaerosWorldMap_1.36.0_Forge_1.20.2.jar.disabled (disabled)

Params:
  --username (I'm not sharing my email) --version 1.20.2 --gameDir D:/Descargas/mmc-cracked-win32/UltimMC/instances/1.20.2/.minecraft --assetsDir D:/Descargas/mmc-cracked-win32/UltimMC/assets --assetIndex 8 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType Ely.by --versionType release --launchTarget forge_client --fml.forgeVersion 48.1.0 --fml.mcVersion 1.20.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230921.100330

Window size: 854 x 480

Java Arguments:
[-javaagent:D:/Descargas/mmc-cracked-win32/UltimMC/injectors/authlib-injector-1.2.4.jar=ely.by, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx2048m, -Duser.language=en]


Minecraft process ID: 31228


[authlib-injector] [INFO] Logging file: D:\Descargas\mmc-cracked-win32\UltimMC\instances\1.20.2\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.4
[authlib-injector] [INFO] Authentication server: https://ely.by
[authlib-injector] [INFO] Redirect to: https://account.ely.by/api/authlib-injector
[authlib-injector] [INFO] Disabled Mojang namespace
Using onesix launcher.

Checking: MC_SLIM
Missing: D:\Descargas\mmc-cracked-win32\UltimMC\libraries\net\minecraft\client\1.20.2-20230921.100330\client-1.20.2-20230921.100330-slim.jar
Some extra libraries are missing! Running the installer to generate them now.
JVM info: Oracle Corporation - 19.0.1 - 19.0.1+10-21
java.net.preferIPv4Stack=true
Created Temporary Directory: C:\Users\USER\AppData\Local\Temp\forge_installer15704342156034616120
  Extracting: /data/client.lzma
Building Processors
===============================================================================
  MainClass: net.minecraftforge.installertools.ConsoleTool
  Classpath:
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\net\minecraftforge\installertools\1.3.0\installertools-1.3.0.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\net\md-5\SpecialSource\1.11.0\SpecialSource-1.11.0.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\com\google\code\gson\gson\2.8.7\gson-2.8.7.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\de\siegmar\fastcsv\2.0.0\fastcsv-2.0.0.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\net\minecraftforge\srgutils\0.4.11\srgutils-0.4.11.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\ow2\asm\asm-commons\9.3\asm-commons-9.3.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\com\google\guava\guava\20.0\guava-20.0.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\com\opencsv\opencsv\4.4\opencsv-4.4.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\ow2\asm\asm-analysis\9.3\asm-analysis-9.3.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\ow2\asm\asm-tree\9.3\asm-tree-9.3.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\ow2\asm\asm\9.3\asm-9.3.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\apache\commons\commons-text\1.3\commons-text-1.3.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\commons-beanutils\commons-beanutils\1.9.3\commons-beanutils-1.9.3.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\org\apache\commons\commons-collections4\4.2\commons-collections4-4.2.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar
    D:\Descargas\mmc-cracked-win32\UltimMC\libraries\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar
  Args: --task, MCP_DATA, --input, D:\Descargas\mmc-cracked-win32\UltimMC\libraries\de\oceanlabs\mcp\mcp_config\1.20.2-20230921.100330\mcp_config-1.20.2-20230921.100330.zip, --output, D:\Descargas\mmc-cracked-win32\UltimMC\libraries\de\oceanlabs\mcp\mcp_config\1.20.2-20230921.100330\mcp_config-1.20.2-20230921.100330-mappings.txt, --key, mappings
java.lang.IllegalAccessError: superclass access check failed: class org.objectweb.asm.tree.ClassNode (in module org.objectweb.asm.tree) cannot access class org.objectweb.asm.ClassVisitor (in unnamed module @0x16c069df) because module org.objectweb.asm.tree does not read unnamed module @0x16c069df
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1013)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1091)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:182)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:821)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassInModuleOrNull(BuiltinClassLoader.java:741)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:665)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:669)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.minecraftforge.installertools.Tasks.<clinit>(Tasks.java:29)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newMethodAccessor(MethodHandleAccessorFactory.java:71)
	at java.base/jdk.internal.reflect.ReflectionFactory.newMethodAccessor(ReflectionFactory.java:159)
	at java.base/java.lang.reflect.Method.acquireMethodAccessor(Method.java:720)
	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
	at java.base/java.lang.Class.getEnumConstantsShared(Class.java:3894)
	at java.base/java.lang.Class.getEnumConstants(Class.java:3869)
	at net.minecraftforge.installertools.ConsoleTool.main(ConsoleTool.java:35)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at net.minecraftforge.installer.actions.PostProcessors.process(PostProcessors.java:226)
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1$ClientInstall4MultiMC.run(InstallerV1.java:35)
	at io.github.zekerzhayard.forgewrapper.installer.util.InstallerV1.runClientInstall(InstallerV1.java:20)
	at io.github.zekerzhayard.forgewrapper.installer.Installer.install(Installer.java:26)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to run processor: java.lang.IllegalAccessError:superclass access check failed: class org.objectweb.asm.tree.ClassNode (in module org.objectweb.asm.tree) cannot access class org.objectweb.asm.ClassVisitor (in unnamed module @0x16c069df) because module org.objectweb.asm.tree does not read unnamed module @0x16c069df
See log for more details.
Process exited with exit code 0 (0x0).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
You're using the wrong Java, please use Java 17
