### ISSUE TITLE
Error upon launch for all post-24w14potato instance versions after attempting to launch 1.21

### ISSUE THREAD

**Issue by daniidsiilva** [UltimMC/Launcher#362]
### Description of bug

Changed version 1.20.6 instance to 1.21. Launching produced an error.
Errors for 1.21 (all snapshots), 1.20.6 (all snapshots), 1.20.5 (down to 24w14a)
24w14potato and down works as intended.

### Steps to reproduce

- Switch a 1.20.6 instance to version 1.21
- Launch

### Suspected cause

Error log of 1.20.6 after attempting to launch 1.21

```
UltimMC version: 0.7.0-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.45]

textures.minecraft.net resolves to:
    [13.107.246.45]

api.mojang.com resolves to:
    [13.107.246.45]


Minecraft folder is:
C:/Users/kengo/Desktop/ultimc/UltimMC/instances/1.20.4/.minecraft


Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe


Checking Java version...
Java is version 17.0.8, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  C:/Users/kengo/Desktop/ultimc/UltimMC/instances/1.20.4/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/datafixerupper/7.0.14/datafixerupper-7.0.14.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-arm64.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3-natives-windows-x86.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  C:/Users/kengo/Desktop/ultimc/UltimMC/libraries/com/mojang/minecraft/1.20.6/minecraft-1.20.6-client.jar

Native libraries:

Params:
  --username dantheman --version 1.20.6 --gameDir C:/Users/kengo/Desktop/ultimc/UltimMC/instances/1.20.4/.minecraft --assetsDir C:/Users/kengo/Desktop/ultimc/UltimMC/assets --assetIndex 16 --uuid <PROFILE ID> --accessToken  --userType local --versionType release

Window size: max (if available)

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -javaagent:C:/Users/kengo/Desktop/ultimc/UltimMC/injectors/authlib-injector-1.2.5.jar=http://localhost:58192, -Dauthlibinjector.noShowServerName]


Minecraft process ID: 17280


[authlib-injector] [INFO] Logging file: C:\Users\kengo\Desktop\ultimc\UltimMC\instances\1.20.4\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: http://localhost:58192
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 07 Jul 2024 17:32:12 +0300
```

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Neptune650** [comment]
You need Java 21, use it.

**Comment by lBEASTl** [comment]
do we always need to download new versions of java when we update minecraft? its quite annoying
