### ISSUE TITLE
crashesh when launch 1.21

### ISSUE THREAD

**Issue by Noobic-craftic** [UltimMC/Launcher#379]
### Description of bug

When i try to launch new instance on 1.21 version (vanilla), but i get a crash with:
 java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll 
How to fix it?

Full log

```
UltimMC version: 0.7.0-custom


Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.67]

textures.minecraft.net resolves to:
    [13.107.246.67]

api.mojang.com resolves to:
    [13.107.246.60]


Minecraft folder is:
K:/UltimMC/instances/MalinaTown 1.21.1/.minecraft


Java path is:
K:/UltimMC/java/jdk-22.0.2/bin/javaw.exe


Checking Java version...
Java is version 22.0.2, using 64-bit architecture, from Oracle Corporation.


Main Class:
  net.minecraft.client.main.Main

Native path:
  K:/UltimMC/instances/MalinaTown 1.21.1/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  K:/UltimMC/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  K:/UltimMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  K:/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  K:/UltimMC/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  K:/UltimMC/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  K:/UltimMC/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  K:/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  K:/UltimMC/libraries/com/mojang/brigadier/1.3.10/brigadier-1.3.10.jar
  K:/UltimMC/libraries/com/mojang/datafixerupper/8.0.16/datafixerupper-8.0.16.jar
  K:/UltimMC/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  K:/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  K:/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  K:/UltimMC/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  K:/UltimMC/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  K:/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  K:/UltimMC/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  K:/UltimMC/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  K:/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  K:/UltimMC/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  K:/UltimMC/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  K:/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  K:/UltimMC/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  K:/UltimMC/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  K:/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  K:/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  K:/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  K:/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  K:/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  K:/UltimMC/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  K:/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  K:/UltimMC/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  K:/UltimMC/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  K:/UltimMC/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  K:/UltimMC/libraries/com/mojang/minecraft/1.21.1/minecraft-1.21.1-client.jar

Native libraries:

Params:
  --username Noobic_craftic --version 1.21.1 --gameDir K:/UltimMC/instances/MalinaTown 1.21.1/.minecraft --assetsDir K:/UltimMC/assets --assetIndex 17 --uuid  --accessToken <КЛЮЧ ДОСТУПА> --userType Ely.by --versionType release

Window size: 854 x 480

Java Arguments:
[-javaagent:K:/UltimMC/injectors/authlib-injector-1.2.5.jar=ely.by, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx6144m, -Duser.language=en]


Minecraft process ID: 11212


[authlib-injector] [INFO] Logging file: K:\UltimMC\instances\MalinaTown 1.21.1\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: https://ely.by
[authlib-injector] [INFO] Redirect to: https://account.ely.by/api/authlib-injector
[authlib-injector] [INFO] Disabled Mojang namespace
Using onesix launcher.

[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[17:07:17] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 1869 milliseconds
[17:07:29] [main/WARN]: Unrecognized user type: Ely.by
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[17:07:30] [main/INFO]: [STDERR]: Failed to start Minecraft:
[17:07:30] [main/INFO]: [STDERR]: java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
[17:07:30] [main/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:174)
[17:07:30] [main/INFO]: [STDERR]: 	at org.lwjgl.system.Library.loadSystem(Library.java:64)
[17:07:30] [main/INFO]: [STDERR]: 	at org.lwjgl.system.Library.<clinit>(Library.java:52)
[17:07:30] [main/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:100)
[17:07:30] [main/INFO]: [STDERR]: 	at fbf.<clinit>(SourceFile:12)
[17:07:30] [main/INFO]: [STDERR]: 	at fbk.<init>(SourceFile:30)
[17:07:30] [main/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(SourceFile:48)
[17:07:30] [main/INFO]: [STDERR]: 	at ac.a(SourceFile:70)
[17:07:30] [main/INFO]: [STDERR]: 	at fgo.a(SourceFile:2542)
[17:07:30] [main/INFO]: [STDERR]: 	at fgo.a(SourceFile:2517)
[17:07:30] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(SourceFile:210)
[17:07:30] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[17:07:30] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[17:07:30] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
[17:07:30] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
[17:07:30] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[17:07:30] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[17:07:30] [main/INFO]: [STDOUT]: Exiting with -1

```

### Steps to reproduce

how to fix this issue

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by MAX2136** [comment]
Having the same exact issue, have you figured it out or why has it been closed?
