### ISSUE TITLE
1.21.1 error 65542 exit code 0

### ISSUE THREAD

**Issue by V01DWARE** [UltimMC/Launcher#387]
### Operating System

Windows 10

### Description of bug

everytime i launch an updated version of MC, it shows this error, is there a way to play with an older OpenGL version? it happens with 1.16 too.

### Steps to reproduce

- make an instance in an updated mc version (like 1.16 and 1.21)
- launch

### Suspected cause

> [17:11:59] [main/WARN]: Unrecognized user type: local
> [authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
> [authlib-injector] [INFO] Httpd is running on port 52712
> [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
> [17:12:04] [Render thread/INFO]: Environment: Environment[sessionHost=http://127.0.0.1:52712/https/sessionserver.mojang.com, servicesHost=http://127.0.0.1:52712/https/api.minecraftservices.com, name=PROD]
> [authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo] with [Yggdrasil Public Key Transformer]
> [17:12:04] [Render thread/INFO]: Setting user: Voidware
> [authlib-injector] [WARNING] An error occurred while processing request [/https/sessionserver.mojang.com/session/minecraft/profile/<PROFILE ID>]
> java.io.UncheckedIOException: java.io.FileNotFoundException: http://localhost:52692/sessionserver/session/minecraft/profile/<PROFILE ID>?unsigned=false
> 	at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryProfile(YggdrasilClient.java:92)
> 	at moe.yushi.authlibinjector.httpd.QueryProfileFilter.handle(QueryProfileFilter.java:82)
> 	at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:142)
> 	at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
> 	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
> 	at java.base/java.lang.Thread.run(Thread.java:1570)
> Caused by: java.io.FileNotFoundException: http://localhost:52692/sessionserver/session/minecraft/profile/<PROFILE ID>?unsigned=false
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:2010)
> 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1615)
> 	at moe.yushi.authlibinjector.util.IOUtils.http(IOUtils.java:49)
> 	at moe.yushi.authlibinjector.yggdrasil.YggdrasilClient.queryProfile(YggdrasilClient.java:90)
> 	... 5 more
> 
> [17:12:04] [Download-1/WARN]: Couldn't look up profile properties for 00d1d5fb-da1f-34aa-bd80-c42f5aba224c
> com.mojang.authlib.exceptions.MinecraftClientException: Failed to read value Internal Server Error
> 	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:32) ~[authlib-6.0.54.jar:?]
> 	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:99) ~[authlib-6.0.54.jar:?]
> 	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.54.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfileUncached(YggdrasilMinecraftSessionService.java:201) ~[authlib-6.0.54.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fetchProfile(YggdrasilMinecraftSessionService.java:171) ~[authlib-6.0.54.jar:?]
> 	at net.minecraft.class_310.method_53464(class_310.java:454) ~[client-intermediary.jar:?]
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
> 	at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
> Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
> 	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-6.0.54.jar:?]
> 	... 9 more
> Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
> 	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:386) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:1047) ~[gson-2.10.1.jar:?]
> 	at com.google.gson.Gson.fromJson(Gson.java:982) ~[gson-2.10.1.jar:?]
> 	at com.mojang.authlib.minecraft.client.ObjectMapper.readValue(ObjectMapper.java:30) ~[authlib-6.0.54.jar:?]
> 	... 9 more
> [17:12:07] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
> [17:12:17] [Render thread/WARN]: Failed to create window: 
> net.minecraft.class_1041$class_4716: GLFW error 65542: WGL: The driver does not appear to support OpenGL
> 	at net.minecraft.class_1041.method_4501(class_1041.java:212) ~[client-intermediary.jar:?]
> 	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.3.jar:?]
> 	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.3.jar:?]
> 	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2058) ~[lwjgl-glfw-3.3.3.jar:?]
> 	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2229) ~[lwjgl-glfw-3.3.3.jar:?]
> 	at net.minecraft.class_1041.redirect$zea000$sodium$wrapGlfwCreateWindow(class_1041.java:1069) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_1041.<init>(class_1041.java:96) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_3682.method_16038(class_3682.java:21) ~[client-intermediary.jar:?]
> 	at net.minecraft.class_310.<init>(class_310.java:505) ~[client-intermediary.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:239) [client-intermediary.jar:?]
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.3.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.3.jar:?]
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.3.jar:?]
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Process exited with exit code 0 (0x0).
> Please note that usually neither the exit code, nor its description are enough to diagnose issues!
> Always upload the entire log and not just the exit code.

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by saifeddine333** [comment]
i have the same issue did you find a solution ?

**Comment by saifeddine333** [comment]
so i downloaded java runtime 21.0.3 and it worked
