### ISSUE TITLE
Cant open any version of forge

### ISSUE THREAD

**Issue by Raidh51** [UltimMC/Launcher#403]
### Operating System

_Windows 11_

### Description of bug

when i try to open forge 1.20.1, forge ver 47.3.12 it gets to the loading screen and immediately just crashes

### Steps to reproduce

-open launcher
-create forge (any version) insatnce
-launch online/offline
-crash without making it to the loading screen

### Suspected cause

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
	at org.lwjgl.system.Library.loadNative(Library.java:327) ~[lwjgl-3.3.1.jar%2370!/:build 7] {}
	at org.lwjgl.system.Library.loadNative(Library.java:224) ~[lwjgl-3.3.1.jar%2370!/:build 7] {}
	at org.lwjgl.openal.ALC.create(ALC.java:119) ~[lwjgl-openal-3.3.1.jar%2366!/:build 7] {}
	at org.lwjgl.openal.ALC.create(ALC.java:76) ~[lwjgl-openal-3.3.1.jar%2366!/:build 7] {}
	at org.lwjgl.openal.ALC.<clinit>(ALC.java:55) ~[lwjgl-openal-3.3.1.jar%2366!/:build 7] {}
	at org.lwjgl.openal.ALC10.nalcIsExtensionPresent(ALC10.java:256) ~[lwjgl-openal-3.3.1.jar%2366!/:build 7] {}
	at org.lwjgl.openal.ALC10.alcIsExtensionPresent(ALC10.java:292) ~[lwjgl-openal-3.3.1.jar%2366!/:build 7] {}
	at com.mojang.blaze3d.audio.Library.m_193468_(Library.java:239) ~[client-1.20.1-20230612.114412-srg.jar%23128!/:?] {re:classloading}
	at com.mojang.blaze3d.audio.Library.<init>(Library.java:149) ~[client-1.20.1-20230612.114412-srg.jar%23128!/:?] {re:classloading}
	at net.minecraft.client.sounds.SoundEngine.<init>(SoundEngine.java:58) ~[client-1.20.1-20230612.114412-srg.jar%23128!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.sounds.SoundManager.<init>(SoundManager.java:61) ~[client-1.20.1-20230612.114412-srg.jar%23128!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:470) ~[client-1.20.1-20230612.114412-srg.jar%23128!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22000.1042 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.22000.2124 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22000.2360 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22000.1641 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22000.2538 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22000.2538 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24090.11 (26d75470953920f90fd0438874501e9d9a31e621):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22000.2176 (WinBuild.160101.0800):Microsoft Corporation
		Oleacc.dll:Active Accessibility Core Component:7.2.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22000.1761 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22000.1042 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22000.1455 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22000.2124 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		directxdatabasehelper.dll:DirectXDatabaseHelper:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		dxgi.dll:DirectX Graphics Infrastructure:10.0.22000.2245 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22000.2538 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22000.2360 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22000.708 (WinBuild.160101.0800):Microsoft Corporation
		ig9icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:27.20.100.8682:Intel Corporation
		igc64.dll:Intel Graphics Shader Compiler for Intel(R) Graphics Accelerator:27.20.100.8682:Intel Corporation
		igdgmm64.dll:User Mode Driver for Intel(R) Graphics Technology:27.20.100.8682:Intel Corporation
		igdml64.dll:Metrics Library for Intel(R) Graphics Technology:27.20.100.8682:Intel Corporation
		inputhost.dll:InputHost:10.0.22000.168 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		java.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		javaw.exe:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		jna6110022195623535552.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:21.0.5.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.22000.71 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		mscms.dll:Microsoft Colour Matching System DLL:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22000.1761 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		ole32.dll:Microsoft OLE for Windows:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22000.1042 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22000.2124 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22000.2360 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
		win32u.dll:Win32u:10.0.22000.2538 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22000.2652 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22000.653 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22000.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:21.0.5.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:182) ~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.12.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) ~[?:?] {}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[?:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[?:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 804257792 bytes (767 MiB) / 1073741824 bytes (1024 MiB) up to 4206886912 bytes (4012 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: Amber Lake
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8682
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.87
	Memory slot #0 type: LPDDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.87
	Memory slot #1 type: LPDDR3
	Virtual memory max (MB): 11948.98
	Virtual memory used (MB): 5444.57
	Swap memory total (MB): 7936.00
	Swap memory used (MB): 877.18
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4012m
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: Intel(R) HD Graphics 620 GL version 4.6.0 - Build 27.20.100.8682, Intel
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.12.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.12.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.12.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.12.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.12.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.3.12-universal.jar                |Forge                         |forge                         |47.3.12             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
	Crash Report UUID: f588ee44-fe5b-4e72-ac31-01ea2b150b93
	FML: 47.3
	Forge: net.minecraftforge:47.3.12
[01:44:17] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID d988f88b-97fa-4b2f-ba17-a44189d947d0
#@!@# Game crashed! Crash report saved to: #@!@# C:\games\mmc-cracked-win32\UltimMC\instances\1.20.1\.minecraft\crash-reports\crash-2024-11-19_01.44.17-client.txt
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### This issue is unique

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Raidh51** [comment]
Disabling the game overlay setting in discord seems to have worked👌
